### ISSUE TITLE
Login And SignUp Buttons not displaying correctly.

### ISSUE THREAD

**Issue by ptvrajsk** [opus-inc/opus-inc.github.io#7]
Login Button and SignUp Buttons not correctly displaying occasionally when a user enters a registered / unregistered email.

Perhaps changing the UI elements in a way that creates a systematic login guide to the user could allow for a better representation of the `Log In` and `Sign Up` prompts on the buttons.

Some brainstorming on this will be necessary.

**Comment by ptvrajsk** [comment]
# Ideas (Select One)
## Progressively input Email, Followed by Password
### Description
On load, the button first says `Enter an email`, when the email field has any value (not blank) it says `Enter Password`. When the user clicks the password input, the app evaluates the input email and changes the button to sign up or login.
### Eval
The issue of the button not responding correctly can occur again as the underlying methodology is still the same. Also, changing it to `Log In`/`Sign Up` before the user enters the password might prompt them to click enter? 
### Outcome
:x:

## Dual Button Options
### Description
Using Semantic UI's Dual Button 
![image](https://user-images.githubusercontent.com/39243082/62196459-a7107380-b3b0-11e9-8b21-bc04b219d9f9.png)
Disable Login Button action if email is invalid or alert user of invalid email if login button is pressed (possibly through prompts or something).
### Outcome
✅ 
### TODO
- [ ] Introduce Semantic UI into the App.
- [ ] Figure out Semantic UI styling (as non-invasive as possible) (hopefully while using their CDN instead of adding it to the project bundle)
- [ ] Make it work ✔️
